services:
  app:
    container_name: "x-straight-check"
    build:
      context: .
    image: "x-straight-check-app"
    restart: "always"
    ports:
      - "20269:8080"
    stdin_open: true
    environment:
      - VERSION=${COMMIT_SHA}
    env_file: .env.docker
    networks:
      - xstraightchecknetwork

  cache:
    image: "redis:7"
    env_file:
      - .env.docker
    command: >
      --requirepass ${REDIS_PASSWORD}
    ports:
      - 6379
    networks:
      - xstraightchecknetwork

networks:
  xstraightchecknetwork: {}
