services:
  app:
    container_name: "x-straight-check"
    build:
      context: .
    image: "x-straight-check-app"
    restart: "always"
    ports:
      - "20269:3000"
    stdin_open: true
    environment:
      - VERSION=${COMMIT_SHA}
    env_file: .env.docker
    networks:
      - xstraightchecknetwork

networks:
  xstraightchecknetwork: {}
